import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import customStyle from './../styles/custom.module.css'
import { AiOutlineHeart } from 'react-icons/ai'
import { MdOutlineModeComment } from 'react-icons/md'
import { RiSendPlaneLine } from 'react-icons/ri'
import { FiSave } from 'react-icons/fi'
import { IoMdHome } from 'react-icons/io'
import { CiSearch } from 'react-icons/ci'
import { MdOutlineExplore } from 'react-icons/md'
import { BiMessageRoundedDetail } from 'react-icons/bi'
import { IoMdHeartEmpty } from 'react-icons/io'
import { BiMessageSquareAdd } from 'react-icons/bi'
import { CgProfile } from 'react-icons/cg'
import { AiOutlineMenu } from 'react-icons/ai'
import image1 from '../public/images/1.jpg'
import image2 from '../public/images/1.jpg'
import image3 from '../public/images/3.jpg'
import image4 from '../public/images/1.jpg'
import image5 from '../public/images/1.jpg'
import image6 from '../public/images/3.jpg'
import image7 from '../public/images/1.jpg'
import image8 from '../public/images/1.jpg'
import image9 from '../public/images/3.jpg'
import image10 from '../public/images/1.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='container-fluid'>
          <div className='row vh-100'>
            <div className='col-2 border-end'>
              <h2 className='py-5'>Instagram</h2>

              <div className='pb-3 d-flex align-items-center'><IoMdHome className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Home</a></div>
              <div className='pb-3 d-flex align-items-center'><CiSearch className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Search</a></div>
              <div className='pb-3 d-flex align-items-center'><MdOutlineExplore className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Explore</a></div>
              <div className='pb-3 d-flex align-items-center'><BiMessageRoundedDetail className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Messages</a></div>
              <div className='pb-3 d-flex align-items-center'><IoMdHeartEmpty className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Notification</a></div>
              <div className='pb-3 d-flex align-items-center'><BiMessageSquareAdd className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Create</a></div>
              <div className='pb-3 d-flex align-items-center'><CgProfile className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>Profile</a></div>
              <div className='pb-3 d-flex align-items-center'><AiOutlineMenu className='fs-2 me-3' /><a className='text-decoration-none text-dark fs-4' href='#'>More</a></div>
            </div>

            <div className='col-6'>
              <div className="row">
                <div className='col-8 offset-4 pt-3'>
                  <div className='border rounded p-3 d-flex justify-content-around'>
                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image1} alt='female-image' width={300} height = {400}/>
                      <label>Christanio</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image2} width={300} height = {400} alt='female-image' />
                      <label>Alina</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image3} width={300} height = {400} alt='female-image' />
                      <label>Aliya</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image4} width={300} height = {400} alt='female-image' />
                      <label>John</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image5} width={300} height = {400} alt='female-image' />
                      <label>Sadia</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image6} width={300} height = {400} alt='female-image' />
                      <label>Smith</label>
                    </div>

                    <div className='d-flex flex-column align-items-center'>
                      <Image className={`rounded-circle ${customStyle.shorts}`} src={image7} width={300} height = {400} alt='female-image' />
                      <label>Mark</label>
                    </div>

                  </div>

                  <div className='border rounded mt-5'>
                    <div className='d-flex align-items-center p-3'>
                      <div>
                        <Image className={`rounded-circle ${customStyle.profileImg}`} src={image8} alt='female-image' width={300} height = {400} />
                      </div>
                      <div className='d-flex flex-column ps-3'>
                        <label>Alina Khan</label>
                        <label className={customStyle.textXsm}>Los angeles</label>
                      </div>
                    </div>

                    <div>
                      <Image className={customStyle.cardImg} src={image9} width={300} height = {400} alt='female-image' />
                    </div>

                    <div className='px-3 pt-2 d-flex justify-content-between'>
                      <div>
                        <AiOutlineHeart className='fs-2' />

                        <MdOutlineModeComment className='fs-2 ms-3' />

                        <RiSendPlaneLine className='fs-2 ms-3' />
                      </div>

                      <div>
                        <FiSave className='fs-3' />
                      </div>
                    </div>

                    <div className='px-3'>
                      <label className={customStyle.textSm}>31,031,086 likes</label>

                      <p className={customStyle.textSm}>
                        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.
                      </p>
                    </div>
                  </div>

                </div>
              </div>
            </div>

            <div className='col-4 px-5 pt-4'>
              <div className='d-flex justify-content-between align-items-center'>
                <div className='d-flex align-items-center p-3'>
                  <div>
                    <Image className={`rounded-circle ${customStyle.profileImg}`} src={image10} width={300} height = {400} alt='female-image' />
                  </div>
                  <div className='d-flex flex-column ps-3'>
                    <label>Alina Khan</label>
                    <label className={customStyle.textXsm}>Los angeles</label>
                  </div>
                </div>

                <div>
                  <label className={`text-primary ${customStyle.textSm}`}>Switch</label>
                </div>
              </div>
            </div>
          </div>

        </div>

      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}